import CustomSelect from "@/Components/CustomSelect";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>WOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "20px" }}>
        <CustomSelect
          options={[
            {
              label: "Manager",
              options: [
                { label: "Jack", value: "jack" },
                { label: "Lucy", value: "lucy" },
              ],
            },
            {
              label: "Engineer",
              options: [{ label: "yiminghe", value: "Yiminghe" }],
            },
          ]}
        />
      </div>
    </>
  );
}
